# ESP-IDF Project Makefile
#
# Este Makefile es una alternativa simple para compilar con ESP-IDF
#

PROJECT_NAME := ws2812_led_demo
IDF_PATH ?= $(HOME)/esp/esp-idf

include $(IDF_PATH)/make/project.mk
